Repository getsops/sops, pull requests merged in 2023-08, with the labels that each got.

#1257 kms: update dependencies
  go.mod
  go.sum
  kms/keysource.go
Labels: keyservice/awskms

#1255 gcpkms: update GCP related dependencies
  gcpkms/keysource.go
  go.mod
  go.sum
Labels: keyservice/gcpkms

#1256 azkv: update dependencies
  README.rst
  azkv/keysource.go
  azkv/keysource_integration_test.go
  go.mod
  go.sum
Labels: keyservice/azkv

#1244 Update various bits of documentation
  CONTRIBUTING.md
  README.rst
  docs/images/cncf-color-bg.svg
Labels: area/documentation

#1060 Add missing --encrypt flag from Vault example
  README.rst
Labels: area/documentation

#899 fix `set` feature when adding a new root hierarchy
  sops.go
  sops_test.go
Labels: bug

#1101 Ensure stable order of SOPS parameters in dotenv file
  stores/dotenv/store.go
  stores/dotenv/store_test.go
Labels: bug, stores/dotenv

#1192 Add documentation on how to use age in .sops.yaml
  README.rst
Labels: area/documentation

#1264 Update dependencies
  go.mod
  go.sum
Labels: dependencies

#1261 version: rewrite command to use GitHub endpoints
  .goreleaser.yaml
  go.mod
  version/version.go
  version/version_test.go
Labels: enhancement
