Repository getsops/sops, pull requests merged in 2023-10, with the labels that each got.

#1272 Enrich AWS authentication documentation
  README.rst
Labels: area/documentation

#1286 Better error reporting for missing gpg binary
  pgp/keysource.go
  pgp/keysource_test.go
Labels: area/keyservice, keyservice/pgp

#1287 Add linting for RST and MD files
  .github/workflows/docs.yml
  CONTRIBUTING.md
  Makefile
Labels: area/CI

#1325 Update dependencies
  go.mod
  go.sum
Labels: dependencies, go

#1049 Respect aws_profile from Keygroup Config
  README.rst
  config/config.go
  config/config_test.go
  kms/keysource.go
  kms/keysource_test.go
Labels: bug, keyservice/awskms
